### ISSUE TITLE
Magic32 function

### ISSUE THREAD

**Issue by 0-x2b** [fengberd/YuRISTools#4]
The `Magic32` function appears to be [CRC32](https://wiki.osdev.org/CRC32). If you examine the lookup table, it's exactly the same as your `Magic32_Table`.

There is also a bug [in your implementation](https://github.com/fengberd/YuRISTools/blob/fec7ad0659150aee04597219d3d4dbf2465f830b/YuRISLib/CheckSum.cs#L102). Replacing that loop with  `for (int r = 0; r < high; r++)`  should fix it.

**Comment by fengberd** [comment]
Thanks for pointing this out, I didn't recognized it because it looks like a 4-registrers hash algorithm, I think that's caused by compiler optimizations.
Anyway, when I created this method, I'm using `euphd` as the input, which gives me the correct result (exactly same as CRC32). The bug only occurs for specified length of string tho.

There's a correct implementation in the same class, I've replaced `Magic32` with it.
